construct-directive:
  trainable_configuration:
    # defines network and environment params
    config_name:
      type: str
      choice: mixing-32-gru-64-hypernet-32-env-8m.yaml
    # defines logic behind trainable construct
    construct_class:
      type: str
      choice: QMIXSharedParamsConstruct

tuner-directive:
  rollout_configuration:
    steps_per_rollout_limit:
      type: int
      choice: 120
    n_rollouts:
      type: int
      choice: 1000
    eval_schedule:
      type: int
      choice: 100
  checkpoint_configuration:
    checkpoint_frequency:
      type: int
      choice: 1000
    checkpoint_at_end:
      type: bool
      choice: true
