architecture-directive:
  construct_configuration:
    training:
      lr:
        type: float
        choice: 0.0005
      gamma:
        type: float
        choice: 0.99
      target_network_update_schedule:
        type: int
        choice: 200
      grad_clip:
        type: float
        choice: 10.0
  drqn_configuration:
    model:
      type: dict
      choice: {
        "observation_size": 80,
        "n_actions": 14,
        "embedding_size": 64,
        "hidden_state_size": 128,
        "n_q_values": 14,
        }
    exploration:
      epsilon_start:
        type: float
        choice: 1.0
      epsilon_min:
        type: float
        choice: 0.05
      epsilon_anneal_time:
        type: flaot
        choice: 500_000
  hypernetwork_configuration:
    model:
      type: dict
      choice: {
        "state_representation_size": 168,
        "hidden_layer_size": 64,
        }
  mixing_head_configuration:
    model:
      choice: {
        "hidden_layer_size": 32,
        }
  device_configuration:
    accelerator:
      type: str
      choice: "cpu"

environment-directive:
  prefix:
    type: string
    choice: "8m"
  num_agents:
    type: int
    choice: 8
  space_params_configuration:
    state_shape:
      type: int
      choice: 168
    single_agent_obs_shape:
      type: int
      choice: 80
    n_actions:
      type: int
      choice: 14
    episode_limit:
      type: int
      choice: 120

memory-directive:
  max_size:
    type: int
    choice: 5_000
  batch_size:
    type: int
    choice: 32
  prioritized:
    type: bool
    choice: false
